version: 2.1

# executor:
#   admin-web:
#     working_directory: /apps/admin-web

jobs:
  build:
    steps:
      - checkout
      - run: echo "this is the build job"
      # - run: yarn install
      # - run: yarn run build
  test:
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
          name: "Build"
      - test
          name: "Test"
